### ISSUE TITLE
Plugin is_admin Hotfix - Alerts are not working

### ISSUE THREAD

**Issue by robert81** [WPWhiteSecurity/WP-Security-Audit-Log#55]
@markdelf @carmelopreeostudios 

I tested the plugin hotfix (https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/pull/51) and can confirm the below alerts are not working:

1. Content alerts (anything related to blog posts, pages and custom posts) are not working.

2. move widget between containers, alert  2045

3. move widget in same container, alert 2071

4. user deletes category, alert 2024

5. user creates category, alert 2023

**Comment by carmelopreeostudios** [comment]
@robert81 I fixed these sensors there was a problem with the Hook,
The alert 2045 is generated always with the alert 2071, I think, it is right, because when you
move a widget from a sidebar to another the position changes

**Comment by robert81** [comment]
@carmelopreeostudios there is still an issue with alert 2071 not being generated, this is the only pending issue with branch 1.5.1. So to confirm, when a widget is moved between containers alert 2045 should be generated + 2071 should always be generated when there is position change.

So if a widget is moved between containers and other widgets changed their poistion in the widget container then alert 2071 should be generated.

**Comment by carmelopreeostudios** [comment]
Hi Robert,
I send you a screen shot of my local,
I tested the alert 2071 and it is working when I move between containers
and when i move in the same container.
Let me know what is exactly the problem

Regards,
Carmelo
[image: Inline images 1]

On 26 March 2015 at 08:57, Robert Abela <notifications@github.com> wrote:

> @carmelopreeostudios <https://github.com/carmelopreeostudios> there is
> still an issue with alert 2071 not being generated, this is the only
> pending issue with branch 1.5.1. So to confirm, when a widget is moved
> between containers alert 2045 should be generated + 2071 should always be
> generated when there is position change.
>
> So if a widget is moved between containers and other widgets changed their
> poistion in the widget container then alert 2071 should be generated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/issues/55#issuecomment-86382750>
> .
>



-- 

*Carmelo Cutrera*
Web developer

*Mobile: *00356 99664357

*Office: *Entrance C, Level 2, Capital Business Centre, Zwejt Street, San
Gwann, SGN 3000. Malta
*Web:* www.preeostudios.com

<http://www.preeostudios.com/>

**Comment by carmelopreeostudios** [comment]
You can see the screenshot here: https://drive.google.com/open?id=0Bx2o3rh_muixQ0FhXzg3TGlRdjQ&authuser=0

**Comment by robert81** [comment]
@carmelopreeostudios ok it seems it is working. I can confirm that on my local setup and on the live website (wpwhitesecurity.com) it is not working. How can we troubleshooting this? I can give you access to the website to do the troubleshooting yourself, or maybe we enable some debug logging in that sensor to see what might be going wrong.

Please advise.

**Comment by carmelopreeostudios** [comment]
@robert81 The sensor checking if the user can edit dashboard,
now I create one debug log and you will send to me

**Comment by robert81** [comment]
@carmelopreeostudios sorry didn't understand that. Do you mean you will create a debug version of the sensor so I can run it and then send you the logs?

**Comment by carmelopreeostudios** [comment]
@robert81 Yes, a debug version

**Comment by carmelopreeostudios** [comment]
@robert81 You can download the debug version

**Comment by robert81** [comment]
@carmelopreeostudios Log sent via email.

**Comment by carmelopreeostudios** [comment]
@robert81 I should have fixed the problem. Can you please test again and get back to me?

**Comment by robert81** [comment]
@carmelopreeostudios nailed it!
